### ISSUE TITLE
Cathryn Wentling - cwentling

### ISSUE THREAD

**Issue by cwentling** [odu-cs625-datavis/public-fall24-mcw#13]

**Comment by NAVYAOGIRALA** [comment]
Can you let me under which professor you have taken data visualization course. Because, I don't see your name in the students list under Professor Weigle

**Comment by cwentling** [comment]
Good Afternoon,

I am in Dr. Weigle's Data Visualization course. I apologize, there may be some confusion about my name. My legal name is Cathryn Wentling, but I go by the nickname Liza, which comes from my middle name Elizabeth. Also, my last name is appearing in ODU's system as Holford, which is my maiden name. I emailed a name change request to the register's office for my last name to appear as my married name, Wentling, but I am still waiting to hear back from them. So, there is a chance that my name on your end is Liza Holford or Cathryn Holford. I apologize for the inconvenience of this.

Let me know if you have any other questions or concerns.

Thank you,
Cathryn (Liza) Wentling
________________________________

**Comment by NAVYAOGIRALA** [comment]
Thank you for the clarification. We have your name listed as Liza E. Holford.

Repo Created: https://github.com/odu-cs625-datavis/Fall24-mcw-cwentling
