### ISSUE TITLE
Brian Hanson, Jr. Github Username: bdhansonjr

### ISSUE THREAD

**Issue by bdhansonjr** [odu-cs625-datavis/public-fall24-mcw#21]
Hi, this issue request is for completing HW0.

**Comment by bdhansonjr** [comment]
Also, my Observable username is: @brian-d-hanson-jr

**Comment by NAVYAOGIRALA** [comment]
Repo created: https://github.com/odu-cs625-datavis/fall24-mcw-bdhansonjr
